# Generated by Django 5.1.3 on 2024-11-08 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en cours", "En cours"),
                            ("terminé", "Terminé"),
                            ("validé", "Validé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date(2024, 11, 8))),
                ("end_date", models.DateField(default=datetime.date(2024, 11, 8))),
                ("start_time", models.TimeField(default=datetime.time(15, 32))),
                ("end_time", models.TimeField(default=datetime.time(15, 32))),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
