# Generated by Django 5.1.3 on 2024-11-08 08:12

import django.db.models.deletion
import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("todoList", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en cours", "En cours"),
                            ("terminé", "Terminé"),
                            ("validé", "Validé"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=tasks.models.Task.get_current_date),
                ),
                ("end_date", models.DateField(default=tasks.models.Task.get_next_day)),
                (
                    "start_time",
                    models.TimeField(default=tasks.models.Task.get_current_time),
                ),
                (
                    "end_time",
                    models.TimeField(default=tasks.models.Task.get_time_plus_one_hour),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="todoList.todolist",
                    ),
                ),
            ],
        ),
    ]
