# Generated by Django 5.1.3 on 2024-11-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        ("todoList", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="todo_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="todoList.todolist",
            ),
        ),
    ]
