# Generated by Django 5.1.3 on 2024-11-07 10:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(default=tasks.models.Task.get_next_day),
        ),
        migrations.AddField(
            model_name="task",
            name="end_time",
            field=models.TimeField(default=tasks.models.Task.get_time_plus_one_hour),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(default=tasks.models.Task.get_current_date),
        ),
        migrations.AddField(
            model_name="task",
            name="start_time",
            field=models.TimeField(default=tasks.models.Task.get_current_time),
        ),
        migrations.AlterField(
            model_name="task", name="status", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=255),
        ),
    ]
