# Generated by Django 5.1.3 on 2024-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_end_date_task_end_time_task_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("en cours", "En cours"),
                    ("terminé", "terminé"),
                    ("validé", "Validé"),
                ],
                max_length=50,
            ),
        ),
    ]
