# Generated by Django 5.1.3 on 2024-11-08 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(default=datetime.time(15, 33)),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(default=datetime.time(15, 33)),
        ),
    ]
