# Generated by Django 5.1.3 on 2024-11-10 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_end_time_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateField(default=datetime.date(2024, 11, 10)),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(default=datetime.time(11, 45)),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(default=datetime.date(2024, 11, 10)),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(default=datetime.time(11, 45)),
        ),
    ]
