# Generated by Django 5.1.3 on 2024-11-10 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_end_time_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(default=datetime.time(12, 57)),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(default=datetime.time(12, 57)),
        ),
    ]
