# Generated by Django 5.1.3 on 2024-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=6)),
                ("address", models.CharField(max_length=255)),
                ("zipcode", models.IntegerField(max_length=5)),
                ("city", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
