# Generated by Django 5.1.3 on 2024-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(unique=True)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=255, null=True)),
                ("zipcode", models.IntegerField(max_length=5, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
