# Generated by Django 5.1.3 on 2024-11-08 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
